# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f85325404d9cc6afbe0a2696b3401c250a6ebcc522424d2e9e4d9a3d0b344299605d26cf561f71a21d31d5e39b1a9a46040ed998108c861ffd121e31a50c4a4
  stripe_publishable_key: pk_test_wAlb0rTpWeR28O4VYcUMOB0z
  stripe_secret_key: sk_test_7W7vxupDHdlbQDYX8pvac53c
test:
  secret_key_base: 6b6605709b8785820c394c13ccd71eecd6263a3def553a49e3858b6f66bef7debfab368e688ca5c28e8321a2f1717bac0318affdaa8c863e35bf1839746597ea
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

shared:
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"]%>
  s3_host_name: <%= ENV["S3_HOST_NAME"] %>
  s3_region: <%= ENV["AWS_REGION"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>